# USA Budget

https://www.whitehouse.gov/omb/budget/Historicals

In this project, I was able to find some historical data on goverment spending since 1976, so this ended up raising my curiosity.  I decided to use this information and plot it in a way that could allow someone to easily analyze the spending in various areas along with being able to compare these trends. Using a dataset obtained from the White House website, I decided to explore these trends.

In [1]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
import plotly as py
from plotly.graph_objs import *
import plotly.tools as tls

In [2]:
init_notebook_mode(connected=True)

In [3]:
usaBudget = pd.DataFrame.from_csv('hist05z1.csv', index_col = None, encoding = "ISO-8859-1") #Import CSV
usaBudget.drop('TQ', 1, inplace=True) #Get rid of TQ Column
usaBudget.head()

,Function and Subfunction,1976,1977,1978,1979,1980,1981,1982,1983,1984,...,2012,2013,2014,2015,2016 estimate,2017 estimate,2018 estimate,2019 estimate,2020 estimate,2021 estimate
0,050 National Defense:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,051 Department of Defense-Military:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Military Personnel,"32,912","34,075","35,724","37,641","41,069","48,462","55,704","61,050","64,866",...,"158,352","153,531","150,188","145,858","145,426","146,389",NaN,NaN,NaN,NaN
3,Operation and Maintenance,"28,731","32,108","34,734","38,042","46,386","55,479","62,461","66,500","70,912",...,"286,775","258,277","262,459","246,575","245,354","251,842",NaN,NaN,NaN,NaN
4,Procurement,"20,991","27,922","29,529","31,428","35,283","48,025","64,462","80,355","86,161",...,"118,321","97,757","100,412","102,108","118,941","112,248",NaN,NaN,NaN,NaN

In [4]:
totals = usaBudget[usaBudget['Function and Subfunction'].str.contains("Total")] #Gets rows that involve totaling
totals

,Function and Subfunction,1976,1977,1978,1979,1980,1981,1982,1983,1984,...,2012,2013,2014,2015,2016 estimate,2017 estimate,2018 estimate,2019 estimate,2020 estimate,2021 estimate
12,"Total, National Defense","97,331","110,150","117,227","126,467","143,859","180,001","216,547","245,043","265,157",...,"681,423","610,157","622,284","598,409","615,396","619,466","594,162","602,355","608,207","623,860"
19,"Total, International Affairs","14,057","8,214","11,575","10,382","17,952","27,352","18,224","10,739","24,547",...,"93,339","40,553","57,489","63,258","59,365","58,129","36,652","39,434","42,835","45,887"
23,"Total, General Science, Space, and Technology","4,266","4,634","5,081","5,570","6,250","6,643","7,218","8,155","8,815",...,"29,227","27,964","29,443","29,922","31,488","31,909","31,917","32,556","33,203","33,866"
29,"Total, Energy","15,169","6,332","10,665","9,843","40,320","11,753","12,770","10,683","7,851",...,"7,745","8,445","5,433","6,394","8,107","8,970","7,912","8,154","10,512","12,138"
36,"Total, Natural Resources and Environment","6,055","9,489","13,651","13,251","13,096","11,171","11,263","13,297","12,276",...,"36,959","41,038","37,721","35,675","41,141","42,167","43,114","43,710","44,142","44,850"
40,"Total, Agriculture","4,760","3,629","6,139","14,630","10,227","13,336","24,075","35,048","11,648",...,"20,860","27,436","24,461","16,942","33,389","25,485","21,496","20,367","22,422","24,015"
48,"Total, Commerce and Housing Credit","12,528","8,818","8,759","9,953","15,333","12,754","11,769","10,171","13,306",...,"12,406","-36,505","-67,658","-2,192","3,162","2,130",384,"3,084","8,692","4,038"
56,"Total, Transportation","10,905","10,507","15,098","19,897","21,483","26,957","24,464","27,080","29,309",...,"88,628","97,860","87,062","85,436","90,368","108,823","122,096","125,677","135,430","133,191"
61,"Total, Community and Regional Development","5,703","13,608","11,173","11,123","11,728","9,966","8,390","9,983","8,899",...,"18,504","51,066","16,532","17,452","18,296","29,599","12,951","13,477","13,979","14,262"
69,"Total, Education, Training, Employment, and So...","22,013","30,493","22,613","33,095","31,689","32,336","26,093","27,602","30,952",...,"91,653","71,170","87,797","119,617","111,990","127,835","122,964","132,879","137,123","143,246"
74,"Total, Health","15,190","17,678","18,945","22,177","24,045","27,024","27,479","25,053","31,629",...,"361,897","338,974","416,582","496,070","524,768","568,317","605,755","643,783","681,844","705,976"
84,"Total, Income Security","74,224","89,124","89,398","88,335","110,344","121,028","114,492","123,941","118,134",...,"548,860","533,629","525,988","515,636","525,882","549,982","557,900","576,509","589,533","604,620"
95,"Total, Veterans Benefits and Services","19,664","19,053","19,023","20,481","21,194","23,150","24,963","25,341","26,483",...,"124,524","136,552","166,232","160,969","164,391","179,216","183,392","194,695","203,154","211,662"
101,"Total, Administration of Justice","3,411","3,706","3,999","4,374","4,530","4,566","4,894","5,518","6,205",...,"55,327","51,659","55,683","60,383","56,902","59,794","60,890","61,976","63,064","64,172"
111,"Total, General Government","12,932","12,948","14,200","12,445","13,226","11,313","11,305","12,026","12,399",...,"26,545","25,992","31,217","21,751","25,425","31,992","28,081","30,329","32,693","35,128"
120,"Total, Net Interest","26,729","29,901","35,459","42,630","52,538","68,767","85,032","89,808","111,102",...,"219,921","220,895","228,968","223,196","240,003","302,697","384,619","459,531","523,016","574,174"
128,"Total, Allowances",..........,..........,..........,..........,..........,..........,..........,..........,..........,...,..........,..........,..........,..........,"7,500","15,000","18,359","20,141","13,743","21,471"
135,"Total, Undistributed Offsetting Receipts","-14,386","-14,879","-15,720","-17,476","-19,942","-28,041","-26,099","-33,976","-31,957",...,"-103,536","-92,785","-88,044","-115,803","-101,156","-108,488","-102,521","-98,492","-101,757","-104,065"
138,Total budget authority,"420,870","468,450","504,565","558,829","670,062","740,300","806,522","869,841","923,384",...,"3,576,168","3,478,366","3,619,008","3,772,713","3,990,913","4,234,877","4,374,189","4,674,166","4,933,090","5,178,555"

In [5]:
nationalDefense = totals.ix[12].values.tolist() #Put each of the rows into lists
internationalAffairs = totals.ix[19].values.tolist()
educationAndEmployment = totals.ix[69].values.tolist()
health = totals.ix[74].values.tolist()
interest = totals.ix[120].values.tolist()
science = totals.ix[23].values.tolist()
transportation = totals.ix[56].values.tolist()
energy = totals.ix[29].values.tolist()
agriculture = totals.ix[40].values.tolist()
incomeSecurity = totals.ix[84].values.tolist()

years = [] #Get each of the years involved
for year in range(1976,2022):
    years.append(year)

In [6]:
trace1 = Scatter(
    x=years, y=nationalDefense,
    line=Line(color='4d4d4d',width=3),
    name='Defense'
)

trace2 = Scatter(
    x=years, y=educationAndEmployment,
    line=Line(color='5da5da', width=3),
    name='Education/Employment'
)

trace3 = Scatter(
    x=years, y=health,
    line=Line(color='faa43a',width=3),
    name='Health'
)

trace4 = Scatter(
    x=years, y=interest,
    line=Line(color='lightgreen',width=3),
    name='Interest'
)

trace5 = Scatter(
    x=years, y=transportation,
    line=Line(color='f17cbo',width=3),
    name='Transportation'
)

trace6 = Scatter(
    x=years, y=incomeSecurity,
    line=Line(color='b2912f',width=3),
    name='Income Security'
)

data1 = Data([trace1,trace2,trace3,trace4,trace5,trace6])
layout1 = Layout(
    title='United States Spending Over Time (in million USD)',
    updatemenus=list([
            dict(
                x=-.08,
                y=1,
                yanchor='top',
                buttons=list([
                        dict(
                            args=['visible', [True,True,True,True,True,True]],
                            label='All',
                            method='restyle'
                            ),
                        dict(
                            args=['visible', [True,False,False,False,False,False]],
                            label='Defense',
                            method='restyle'
                            ),
                        dict(
                            args=['visible', [False,True,False,False,False,False]],
                            label='Education',
                            method='restyle'
                            ),
                        dict(
                            args=['visible', [False,False,True,False,False,False]],
                            label='Health',
                            method='restyle'
                            ),
                        dict(
                            args=['visible', [False,False,False,True,False,False]],
                            label='Interest',
                            method='restyle'
                            ),
                        dict(
                            args=['visible', [False,False,False,False,True,False]],
                            label='Transportation',
                            method='restyle'
                            ),
                        dict(
                            args=['visible', [False,False,False,False,False,True]],
                            label='Income Security',
                            method='restyle'
                        )
                        
                    ])
            )
        ])
)






fig1 = Figure(data=data1, layout=layout1)

In [8]:
trace1 = Scatter(
    x=years, y=science,
    line=Line(color='4d4d4d',width=3),
    name='Science'
)

trace2 = Scatter(
    x=years, y=energy,
    line=Line(color='5da5da', width=3),
    name='Energy'
)

trace3 = Scatter(
    x=years, y=internationalAffairs,
    line=Line(color='faa43a',width=3),
    name='International Affairs'
)

trace4 = Scatter(
    x=years, y=agriculture,
    line=Line(color='lightgreen',width=3),
    name='Agriculture'
)


data2 = Data([trace1,trace2,trace3,trace4])
layout2 = Layout(
    title='United States Spending Over Time (in million USD)',
    updatemenus=list([
            dict(
                x=-.08,
                y=1,
                yanchor='top',
                buttons=list([
                        dict(
                            args=['visible', [True,True,True,True]],
                            label='All',
                            method='restyle'
                            ),
                        dict(
                            args=['visible', [True,False,False,False]],
                            label='Science',
                            method='restyle'
                            ),
                        dict(
                            args=['visible', [False,True,False,False]],
                            label='Energy',
                            method='restyle'
                            ),
                        dict(
                            args=['visible', [False,False,True,False]],
                            label='International',
                            method='restyle'
                            ),
                        dict(
                            args=['visible', [False,False,False,True]],
                            label='Agriculture',
                            method='restyle'
                            )
                        
                    ])
            )
        ])
)


fig2 = Figure(data=data2, layout=layout2) #

---
## Final Graph - USA Budget

The two charts below are the final outcome of the work that was put together. The x is the year, with 2016 and beyond being estimates as to where this budget will go. The y axis is the amount of money spent in each area at any given time, in millions of dollars. Due to the amount of lines, I decided to plot the information on two seperate graphs, with the first one being dedicated to higher budget spending, where over 100,000 million were spent, while the second graph is dedicated to lower budget spending, where spending did not exceed 100,000 million. This graph, to me, raised some very interesting points. As expected, the amount that is being spent is increasing every year. However, what came to a surprise to me was the spending on health. Within the last few years, the amount of spending in health rose greatly, and it is expected to continue rising quickly, surpasing both income security and defense. In addition, I found it very interesting that income security appears to be catching up to defense also.

In [9]:
py.offline.iplot(fig1) #High spending areas

In [10]:
py.offline.iplot(fig2) #Low spending areas